export const Strings = {
  appName: 'PiyariFamily',
  tagline: 'Made in Heaven',
  splashTagline: 'made in heaven',

  welcomeBack: 'Welcome',
  loginSubtitle: 'Meet Your Soulmate',
  emailLabel: 'Email Address',
  emailPlaceholder: 'you@example.com',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Enter your password',
  forgotPassword: 'Forgot Password?',
  logIn: 'Log In',
  or: 'or',
  continueGoogle: 'Continue with Google',
  continueApple: 'Continue with Apple',
  noAccount: "Don't have an account?",
  createAccount: 'Create Account',

  createYourAccount: 'Create Your Account',
  signUpSubtitle: 'Start your journey to find your soulmate',
  fullNameLabel: 'Full Name',
  fullNamePlaceholder: 'Enter your full name',
  signUpEmailPlaceholder: 'Enter your email',
  phoneNumberLabel: 'Phone Number',
  phoneNumberPlaceholder: 'Enter your phone number',
  createPasswordPlaceholder: 'Create a password',
  confirmPasswordLabel: 'Confirm Password',
  confirmPasswordPlaceholder: 'Confirm your password',
  termsPrefix: 'I agree to the ',
  termsOfService: 'Terms of Service',
  termsAnd: ' and ',
  privacyPolicy: 'Privacy Policy',
  alreadyHaveAccount: 'Already have an account?',
  logInLink: 'Log In',

  verifyYourEmail: 'Verify Your Email',
  verifyEmailSubtitle:
    "We've sent a 6-digit code to your email address. Please enter it below.",
  verifyAndContinue: 'Verify & Continue',
  spamFolderHint: "Check your spam folder if you don't see the email.",

  forgotPasswordTitle: 'Forgot Password?',
  forgotPasswordSubtitle:
    "No worries! Enter your registered email and we'll send you a reset code.",
  secureOtpHint: "We'll send a secure OTP to this email",
  sendResetCode: 'Send Reset Code',
  backToLogIn: 'Back to Log In',

  checkYourEmail: 'Check Your Email',
  checkEmailSubtitle:
    "We've sent a 6-digit verification code to your email address. Enter it below to continue.",
  verifyCode: 'Verify Code',

  codeVerifiedTitle: 'Code Verified! ✓',
  codeVerifiedSubtitle:
    'Your identity has been confirmed. You can now set a new password for your account.',
  setNewPassword: 'Set New Password',
  codeVerifiedStep: 'Step 3 of 4 · Almost there 💕',

  setNewPasswordTitle: 'Set New Password',
  setNewPasswordSubtitle:
    'Create a strong password to keep your account secure.',
  newPasswordLabel: 'New Password',
  newPasswordPlaceholder: 'Enter new password',
  confirmNewPasswordLabel: 'Confirm Password',
  confirmNewPasswordPlaceholder: 'Confirm your new password',
  resetPassword: 'Reset Password',

  passwordResetTitle: 'Password Reset!',
  passwordResetSubtitle:
    'Your password has been successfully updated. Your account is now secure.',
  secured: 'Secured',
  protected: 'Protected',
  goToLogIn: 'Go to Log In',

  welcomeBackTitle: 'Welcome Back!',
  welcomeBackSubtitle:
    'Your account is ready. Log in to continue your journey to finding your perfect life partner.',
  passwordResetSuccessMessage: 'Password successfully reset',
  logInNow: 'Log In Now',
  needHelpContactSupport: 'Need help? Contact Support',

  onboardingTitle: 'Find Your Perfect Life Partner',
  onboardingTitle1: 'Find Your Perfect Life Partner',
  onboardingSubtitle1:
    'Millions of verified profiles. Trusted by families across the world.',
  onboardingTitle2: 'Built for Real Connections',
  onboardingSubtitle2:
    'Match with profiles that share your values, culture, and family traditions.',
  onboardingTitle3: 'Start Your Story Today',
  onboardingSubtitle3:
    'Create your profile in minutes and take the first step toward forever.',
  getStarted: 'Get Started',
  onboardingVerified: 'Verified',
  onboardingMillions: 'Millions',
  onboardingPrivate: 'Private',
  onboardingMatches: 'Matches',
  onboardingFamilies: 'Families',
  onboardingTrusted: 'Trusted',
  onboardingEasySetup: 'Easy Setup',
  onboardingSecure: 'Secure',
  onboardingForever: 'Forever',
  homeGreeting: 'Good Morning, Hamza',
  homeSubtitle: 'Here are your best matches today',
  newBadge: 'New',
  verifiedBadge: 'Verified ✓',
  suggestedMatches: 'Suggested Matches',
  seeAll: 'See All',
  tabHome: 'Home',
  tabSearch: 'Search',
  tabMessages: 'Messages',
  tabLike: 'Like',
  tabProfile: 'Profile',

  selectCountryTitle: 'Select Your Country',
  selectCountrySubtitle:
    'Choose your country to personalize your experience',
  searchCountryPlaceholder: 'Search country...',
  continueBtn: 'Continue',

  tellUsAboutYouTitle: 'Tell Us About You',
  tellUsAboutYouSubtitle: "Let's start with your basic details",
  basicInfoStep: 'Step 1 of 6 — Basic Info',
  genderLabel: 'Gender',
  genderMale: 'Male',
  genderFemale: 'Female',
  dateOfBirthLabel: 'Date of Birth',
  dateOfBirthPlaceholder: 'DD / MM / YYYY',
  ageYears: 'years',
};
