export const Strings = {
  appName: 'PiyariFamily',
  tagline: 'Made in Heaven',
  splashTagline: 'made in heaven',

  welcomeBack: 'Welcome',
  loginSubtitle: 'Trust The Trustworthy',
  emailLabel: 'Email Address',
  emailPlaceholder: 'you@example.com',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Enter your password',
  forgotPassword: 'Forgot Password?',
  logIn: 'Log In',
  or: 'or',
  continueGoogle: 'Continue with Google',
  continueApple: 'Continue with Apple',
  noAccount: "Don't have an account?",
  createAccount: 'Create Account',

  createYourAccount: 'Create Your Account',
  signUpSubtitle: 'Start your journey to find your soulmate',
  fullNameLabel: 'Full Name',
  fullNamePlaceholder: 'Enter your full name',
  signUpEmailPlaceholder: 'Enter your email',
  phoneNumberLabel: 'Phone Number',
  phoneNumberPlaceholder: 'Enter your phone number',
  createPasswordPlaceholder: 'Create a password',
  confirmPasswordLabel: 'Confirm Password',
  confirmPasswordPlaceholder: 'Confirm your password',
  termsPrefix: 'I agree to the ',
  termsOfService: 'Terms of Service',
  termsAnd: ' and ',
  privacyPolicy: 'Privacy Policy',
  alreadyHaveAccount: 'Already have an account?',
  logInLink: 'Log In',

  verifyYourEmail: 'Verify Your Email',
  verifyEmailSubtitle:
    "We've sent a 6-digit code to your email address. Please enter it below.",
  verifyAndContinue: 'Verify & Continue',
  spamFolderHint: "Check your spam folder if you don't see the email.",

  forgotPasswordTitle: 'Forgot Password?',
  forgotPasswordSubtitle:
    "No worries! Enter your registered email and we'll send you a reset code.",
  secureOtpHint: "We'll send a secure OTP to this email",
  sendResetCode: 'Send Reset Code',
  backToLogIn: 'Back to Log In',

  checkYourEmail: 'Check Your Email',
  checkEmailSubtitle:
    "We've sent a 6-digit verification code to your email address. Enter it below to continue.",
  verifyCode: 'Verify Code',

  codeVerifiedTitle: 'Code Verified! ✓',
  codeVerifiedSubtitle:
    'Your identity has been confirmed. You can now set a new password for your account.',
  setNewPassword: 'Set New Password',
  codeVerifiedStep: 'Step 3 of 4 · Almost there 💕',

  setNewPasswordTitle: 'Set New Password',
  setNewPasswordSubtitle:
    'Create a strong password to keep your account secure.',
  newPasswordLabel: 'New Password',
  newPasswordPlaceholder: 'Enter new password',
  confirmNewPasswordLabel: 'Confirm Password',
  confirmNewPasswordPlaceholder: 'Confirm your new password',
  resetPassword: 'Reset Password',

  passwordResetTitle: 'Password Reset!',
  passwordResetSubtitle:
    'Your password has been successfully updated. Your account is now secure.',
  secured: 'Secured',
  protected: 'Protected',
  goToLogIn: 'Go to Log In',

  welcomeBackTitle: 'Welcome Back!',
  welcomeBackSubtitle:
    'Your account is ready. Log in to continue your journey to finding your perfect life partner.',
  passwordResetSuccessMessage: 'Password successfully reset',
  logInNow: 'Log In Now',
  needHelpContactSupport: 'Need help? Contact Support',

  onboardingTitle: 'Find Your Perfect Life Partner',
  onboardingTitle1: 'Find Your Perfect Life Partner',
  onboardingSubtitle1:
    'Millions of verified profiles. Trusted by families across the world.',
  onboardingTitle2: 'Built for Real Connections',
  onboardingSubtitle2:
    'Match with profiles that share your values, culture, and family traditions.',
  onboardingTitle3: 'Start Your Story Today',
  onboardingSubtitle3:
    'Create your profile in minutes and take the first step toward forever.',
  getStarted: 'Get Started',
  onboardingVerified: 'Verified',
  onboardingMillions: 'Millions',
  onboardingPrivate: 'Private',
  onboardingMatches: 'Matches',
  onboardingFamilies: 'Families',
  onboardingTrusted: 'Trusted',
  onboardingEasySetup: 'Easy Setup',
  onboardingSecure: 'Secure',
  onboardingForever: 'Forever',
  homeGreeting: 'Good Morning, Hamza',
  homeSubtitle: 'Here are your best matches today',
  newBadge: 'New',
  verifiedBadge: 'Verified ✓',
  suggestedMatches: 'Suggested Matches',
  seeAll: 'See All',
  tabHome: 'Home',
  tabSearch: 'Search',
  tabMessages: 'Messages',
  tabLike: 'Like',
  tabProfile: 'Profile',

  selectCountryTitle: 'Select Your Country',
  selectCountrySubtitle: 'Choose your country to personalize your experience',
  searchCountryPlaceholder: 'Search country...',
  continueBtn: 'Continue',

  tellUsAboutYouTitle: 'Tell Us About You',
  tellUsAboutYouSubtitle: "Let's start with your basic details",
  basicInfoStep: 'Step 1 of 6 — Basic Info',
  genderLabel: 'Gender',
  genderMale: 'Male',
  genderFemale: 'Female',
  dateOfBirthLabel: 'Date of Birth',
  dateOfBirthPlaceholder: 'DD / MM / YYYY',
  ageYears: 'years',
  maritalStatusPlaceholder: 'Select marital status',

  educationStep: 'Step 2 of 6 — Education',
  yourEducationTitle: 'Your Education',
  yourEducationSubtitle: 'Help visitors know your academic background',
  highestQualificationLabel: 'Highest Qualification',
  selectQualificationPlaceholder: 'Select qualification',
  fieldOfStudyLabel: 'Field of Study',
  fieldOfStudyPlaceholder: 'e.g. Computer Science, Medicine',
  universityLabel: 'University / College Name',
  universityPlaceholder: 'Enter institution name',
  graduationYearLabel: 'Graduation Year',
  graduationYearPlaceholder: 'e.g. 2018',

  careerStep: 'Step 3 of 6 — Career',
  yourCareerTitle: 'Your Career',
  yourCareerSubtitle: 'Share your professional background',
  employmentTypeLabel: 'Employment Type',
  employed: 'Employed',
  selfEmployed: 'Self-Employed',
  business: 'Business',
  jobTitleLabel: 'Job Title / Designation',
  jobTitlePlaceholder: 'e.g. Software Engineer, Doctor',
  companyLabel: 'Company / Organization',
  companyPlaceholder: 'Enter company name',
  monthlyIncomeLabel: 'Monthly Income',
  selectIncomeRangePlaceholder: 'Select income range',
  residenceStatusPlaceholder: 'Select residence status',

  physicalDetailsStep: 'Step 4 of 6 — Physical Details',
  physicalDetailsTitle: 'Physical Details',
  physicalDetailsSubtitle: 'Optional — helps find compatible matches',
  heightLabel: 'Height',
  selectFeetPlaceholder: 'Select Feet',
  selectInchesPlaceholder: 'Select Inches',
  weightLabel: 'Weight',
  weightPlaceholder: 'e.g. 65 kg',
  optional: 'Optional',
  bodyTypeLabel: 'Body Type',
  complexionLabel: 'Complexion',
  physicalDisabilityLabel: 'Any physical disability?',
  physicalDetailsNotice:
    'Physical details are optional and can be updated anytime from your profile.',

  faithCommunityStep: 'Step 5 of 6 — Religion & Community',
  faithCommunityTitle: 'Faith & Community',
  faithCommunitySubtitle:
    'Optional — helps find culturally compatible matches',
  selectReligionPlaceholder: 'Select religion',
  communityCasteLabel: 'Community / Caste',
  communityCastePlaceholder: 'e.g. Sunni, Brahmin, Punjabi',
  sectLabel: 'Sect / Sub-community',
  sectPlaceholder: 'e.g. Shia, Sunni, Hanafi',
  selectMotherTonguePlaceholder: 'Select mother tongue',
  selectLanguagesPlaceholder: 'Select languages',
  maxLanguagesHint: 'You can select maximum 5 languages.',
  faithCommunityNotice:
    'Religious details are optional and used only for match filtering.',

  profilePhotosStep: 'Step 6 of 6 — Profile Photos',
  addPhotosTitle: 'Add Your Photos',
  addPhotosSubtitle:
    'Add at least 1 photo to continue. You can upload up to 6 photos, and your first photo will be shown as your main profile picture.',
  mainPhoto: 'Main',
  addPhoto: 'Add Photo',
  photosReviewNotice: 'Photos are reviewed for authenticity.',
  completeProfile: 'Complete Profile',
  addPhotoRequired: 'Please add at least 1 photo to continue',

  profileReadyTitle: 'Congratulations Your Profile is',
  profileReadyHighlight: 'Ready!',
  profileReadySubtitle:
    "You're all set to begin your journey and discover meaningful matches made just for you.",

  aboutPrefix: 'About',
  basicDetails: 'Basic Details',
  otherLanguages: 'Other Languages',
  interests: 'Interests',
  educationLabel: 'Education',
  professionLabel: 'Profession',
  religionLabel: 'Religion',
  residentialStatusLabel: 'Residence Status',
  owned: 'Owned',
  ageDetail: 'Age',
  cityDetail: 'City',
  heightDetail: 'Height',
  maritalStatusDetail: 'Marital Status',
  communityDetail: 'Community',
  motherTongueDetail: 'Mother Tongue',
  neverMarried: 'Never Married',
  sendInterest: 'Send Interest',
  nextBtn: 'Next',
  itsAMatch: "It's a Match!",
  matchSubtitle: 'You and {name} both liked each other!',
  sendAMessage: 'Send a Message',
  keepFinding: 'Keep Finding',
  interestSentNotice:
    'Your interest has been sent. {name} will be notified and can respond within 7 days.',
  potentialMatches: 'Potential matches for you',
  ayeshaAbout:
    'I am a family-oriented person who values honesty, kindness, and meaningful connections. I enjoy reading, traveling, and spending quality time with loved ones. Looking for a life partner who shares similar values and dreams of building a beautiful future together.',

  shortlisted: 'Shortlisted',
  profilesILiked: 'Profiles I Liked',
  likedMe: 'Liked Me',
  viewProfile: 'View Profile',
  filterMatches: 'Filter Matches',
  filterMatchesSubtitle:
    'Refine your matches to find the perfect partner',
  reset: 'Reset',
  ageRange: 'Age Range',
  locationLabel: 'Location',
  cityOrState: 'City or State',
  incomeRange: 'PKR Income Range',
  applyFilters: 'Apply Filters',
  clearAll: 'Clear All',

  findYourMatch: 'Find Your Match',
  searchPlaceholder: 'Search by name, city, profession...',
  quickFilters: 'Quick Filters',
  nearMe: 'Near Me',
  verifiedProfiles: 'Verified',
  newProfiles: 'New Profiles',
  recentSearches: 'Recent Searches',

  messagesTitle: 'Messages',
  searchConversations: 'Search conversations...',
  chatRequests: 'Chat Requests',
  reviewBeforeAccepting: 'Review before accepting',
  chatRequestsNotice: 'Only accept requests from verified profiles you trust',
  pendingRequests: 'Pending Requests',
  onlineNow: 'Online now',
  typeMessage: 'Type a message...',
  decline: 'Decline',
  accept: 'Accept',
  today: 'Today',
  verifiedLabel: 'Verified',

  settings: 'Settings',
  editProfile: 'Edit Profile',
  referAndEarn: 'Refer & Earn',
  rewards: 'REWARDS',
  referSubtitle: 'Invite friends and earn reward points',
  profilePhotosVisibility: 'PROFILE PHOTOS VISIBILITY',
  profilePicture: 'Profile Picture',
  additionalPhotos: 'Additional Photos',
  accountSection: 'ACCOUNT',
  updatePersonalDetails: 'Update your personal details',
  verifyYourProfile: 'Verify Your Profile',
  verifyProfileSubtitle: 'By your phone number OTP',
  securitySection: 'SECURITY',
  changePassword: 'Change Password',
  updateLoginPassword: 'Update your login password',
  subscriptionSection: 'SUBSCRIPTION',
  myPlan: 'My Plan',
  vipPlanActive: 'VIP Plan · Active',
  supportSection: 'SUPPORT',
  helpCenter: 'Help Center',
  helpCenterSubtitle: 'FAQs and guides',
  contactSupport: 'Contact Support',
  contactSupportSubtitle: "We're here to help you",
  termsAndConditions: 'Terms & Conditions',
  termsSubtitle: 'Please read our terms before using the service.',
  rateTheApp: 'Rate the App',
  rateAppSubtitle: 'Share your experience',
  dangerZone: 'DANGER ZONE',
  deactivateAccount: 'Deactivate / Delete Account',
  deactivateSubtitle: 'Permanently remove your data',

  editProfileTitle: 'Edit Profile',
  save: 'Save',
  changePhoto: 'Change Photo',
  personalInfoSection: 'PERSONAL INFO',
  contactInfoSection: 'CONTACT INFO',
  lifestyleSection: 'LIFESTYLE',
  aboutMe: 'About Me',
  aboutMePlaceholder: 'Tell others about yourself...',
  editProfileNotice:
    'Your information is safe and only shared with matches you approve.',
  saveChanges: 'Save Changes',
  selectLanguage: 'Select language',
  community: 'Community',
  heightUnitFt: 'ft',
  heightUnitIn: 'in',
};
