export const Images = {
  splashIllustration: require('./images/splash_illustration.png'),
  appLogo: require('./images/Background.png'),
  googleIcon: require('./images/SVG.png'),
  codeVerifiedIllustration: require('./images/Container.png'),
  passwordResetIllustration: require('./images/Margin.png'),
  starIcon: require('./images/star.png'),
  handshakeIcon: require('./images/handshake.png'),
  heartIcon: require('./images/heart.png'),
  resetSuccessCheck: require('./images/Background (3).png'),
  onboardingIllustration: require('./images/image 3 (4).png'),
  OnBoardingPic: require('./images/OnBoarding.png'),
  verifiedIcon: require('./images/Verified.png'),
  millionsIcon: require('./images/Millions.png'),
  privateIcon: require('./images/Private.png'),
  backArrowIcon: require('./images/BackArrow.png'),
  confirmPasswordIcon: require('./images/Confirm.png'),
  femaleProfile: require('./images/female1.png'),
  femaleProfile2: require('./images/female2.png'),
  maleProfile: require('./images/male2.png'),
  religionIcon: require('./images/religion.png'),
  fieldStudyIcon: require('./images/fieldStudy.png'),
  universityIcon: require('./images/university.png'),
  calendarIcon: require('./images/Calender.png'),
  companyIcon: require('./images/company.png'),
  incomeIcon: require('./images/income.png'),
  feetIcon: require('./images/feet.png'),
  inchesIcon: require('./images/inches.png'),
  profileReadyIllustration: require('./images/ProfileReady.png'),
  communityIcon: require('./images/community.png'),
  msgTextIcon: require('./images/msgtext.png'),
  profileBoostIcon: require('./images/profileBoast.png'),
  filterIcon: require('./images/filter.png'),
};
